### ISSUE TITLE
Git clone from external not work

### ISSUE THREAD

**Issue by crsgarcias** [jboss-dockerfiles/business-central#16]
I can´t clone a git repository

My version is jbpm 7.15.0.Final

![image](https://user-images.githubusercontent.com/25749111/70755218-d93ac600-1cfe-11ea-9d4f-b885390b8713.png)

In my jbpm-console
![image](https://user-images.githubusercontent.com/25749111/70755257-efe11d00-1cfe-11ea-8946-d32619fc3462.png)

In local instance without docker I configure like this, and it is work
![image](https://user-images.githubusercontent.com/25749111/70755313-21f27f00-1cff-11ea-8b8e-7a2e0f31d4d6.png)

Please I need Help!

**Comment by mbiarnes** [comment]
Hi folks,
Can you please send your questions to drools-usage@gmail.com or drools-setup@gmail.com - I think here is more people that may help you.
Thank you.
