### ISSUE TITLE
Business Central Showcase - Can't edit files

### ISSUE THREAD

**Issue by nevius** [jboss-dockerfiles/business-central#2]
Hello,

I wanted to try Business Central, so I downloaded and ran the showcase docker image using the following command (under Windows):

`docker run -p 8080:8080 -p 8001:8001 -d --name business-central-workbench-showcase jboss/business-central-workbench-showcase:latest`

It succesfully started and I logged in with admin/admin and went to use a sample project (Mortgages).

Sadly I get an unexpected error when trying to edit any of the files, like Applicant.java or CreditApproval.rdslr.

![image](https://user-images.githubusercontent.com/1815249/60017678-a259f080-9689-11e9-8350-648d884a29e5.png)

The error details are as follows:

`{"ToSubject":"org.kie.workbench.common.services.shared.project.KieModuleService:RPC.resolvePackage:org.uberfire.backend.vfs.Path::80:RespondTo:RPC"} | Uncaught exception: Client-side exception occurred although RPC call succeeded. Caused by: (TypeError) : Cannot read property 'Mode' of undefined`

Can anyone help me with this issue? Thank you very much.

**Comment by snimmagadda1** [comment]
I've gotten some unexpected errors but mostly click out and/or view the logs of the container. I've found I'm still able to work w/ the demos. What does docker logs <container_name> output?
