### ISSUE TITLE
Support for REST API

### ISSUE THREAD

**Issue by MarcelGeo** [jboss-dockerfiles/business-central#23]
https://access.redhat.com/documentation/en-us/red_hat_jboss_bpm_suite/6.0/html/development_guide/chap-rest_api

In this article, jBPM REST API is documented, it is not possible to use this re4st API with image. Or?

**Comment by mbiarnes** [comment]
Hi Marcel,
Can you please send your questions to drools-usage@gmail.com or drools-setup@gmail.com - I think here is more people that may help you.
Thank you.
