### ISSUE TITLE
Non-Root User not working in Openshift

### ISSUE THREAD

**Issue by ckvtvm-arch** [jboss-dockerfiles/business-central#26]
Changed the JBoss user to a non-root user in docker file and build the image, but have permission issues in openshift post image deployment  - permission denied for server.log.

Please advise on any solutions.

**Comment by mbiarnes** [comment]
Hi,
Btw in the Note it says:

- This image is not intended to be run on cloud environments such as RedHat OpenShift or Amazon EC2, as it does not meet all the requirements. 

Can you please send your questions to drools-usage@gmail.com or drools-setup@gmail.com - I think here is more people that may help you.
Thank you.

**Comment by ckvtvm-arch** [comment]
It worked once in Openshift , but I don’t have the reference now.  Did we changed in the latest version of the image in terms of user or group ? 
Someone suggested me to attach to persistent volume in Openshift , it will work 





Sent from Yahoo Mail for iPhone


On Monday, May 4, 2020, 2:37 AM, Michael Biarnés Kiefer <notifications@github.com> wrote:




Hi,
Btw in the Note it says:
   
   - This image is not intended to be run on cloud environments such as RedHat OpenShift or Amazon EC2, as it does not meet all the requirements.

Can you please send your questions to drools-usage@gmail.com or drools-setup@gmail.com - I think here is more people that may help you.
Thank you.

**Comment by ckvtvm-arch** [comment]
Let me see if this works:
USER root
RUN chgrp -R 0 $JBOSS_HOME &&\
chmod -R g+rw $JBOSS_HOME

**Comment by ckvtvm-arch** [comment]
I know that it may not work in OCP, but i am confident as it worked earlier in openshift .

My initial issue with respect to accessing application users /roles properties is resolved, but right now i am into a different issue in OCP

Failed to read or configure the org.jboss.logmanager.LogManager
/opt/jboss/wildfly/standalone/log/server.log (Permission denied)

I have done a /bin/bash in my container in my docker and i dont see the log folder. do you want me to create a dummy folder and a dummy file for server/server.log  ?.

**Comment by ckvtvm-arch** [comment]
Email bounced back from both DL - drools-usage and drools-setup Gmail 


Sent from Yahoo Mail for iPhone


On Monday, May 4, 2020, 1:13 PM, chenthil kumar <ckv.tvm@yahoo.com> wrote:

It worked once in Openshift , but I don’t have the reference now.  Did we changed in the latest version of the image in terms of user or group ? 
Someone suggested me to attach to persistent volume in Openshift , it will work 





Sent from Yahoo Mail for iPhone


On Monday, May 4, 2020, 2:37 AM, Michael Biarnés Kiefer <notifications@github.com> wrote:




Hi,
Btw in the Note it says:
   
   - This image is not intended to be run on cloud environments such as RedHat OpenShift or Amazon EC2, as it does not meet all the requirements.

Can you please send your questions to drools-usage@gmail.com or drools-setup@gmail.com - I think here is more people that may help you.
Thank you.

**Comment by mbiarnes** [comment]
I am so sorry - I gave you the wrong addresses:
drools-setup@googlegroups.com 
and
drools-usage@googlegroups.com

**Comment by ckvtvm-arch** [comment]
No probs , I send to the right group now. 


Sent from Yahoo Mail for iPhone


On Tuesday, May 5, 2020, 3:07 AM, Michael Biarnés Kiefer <notifications@github.com> wrote:




I am so sorry - I gave you the wrong addresses:
drools-setup@googlegroups.com
and
drools-usage@googlegroups.com

**Comment by ckvtvm-arch** [comment]
Also do you know how I can get the deployment YAML for  jBpm 7.1 or 7.2 . Is it a licensed one such that I cannot get it .
I am thinking whether I can change the template for the images which are already present in my  openshift ! 


Sent from Yahoo Mail for iPhone


On Tuesday, May 5, 2020, 3:51 PM, chenthil kumar <ckv.tvm@yahoo.com> wrote:

No probs , I send to the right group now. 


Sent from Yahoo Mail for iPhone


On Tuesday, May 5, 2020, 3:07 AM, Michael Biarnés Kiefer <notifications@github.com> wrote:




I am so sorry - I gave you the wrong addresses:
drools-setup@googlegroups.com
and
drools-usage@googlegroups.com

**Comment by ckvtvm-arch** [comment]
Also do you know how I can get the deployment YAML for  jBpm 7.1 or 7.2 . Is it a licensed one such that I cannot get it .
I am thinking whether I can change the template for the images which are already present in my  openshift ! 

Sent from Yahoo Mail for iPhone


On Tuesday, May 5, 2020, 3:07 AM, Michael Biarnés Kiefer <notifications@github.com> wrote:




I am so sorry - I gave you the wrong addresses:
drools-setup@googlegroups.com
and
drools-usage@googlegroups.com

**Comment by ckvtvm-arch** [comment]
Finally it worked in openshift , but I am not able to find the kie server configuration and also not able to add it in business central
