### ISSUE TITLE
Can't change server hostname

### ISSUE THREAD

**Issue by hmaracic** [jboss-dockerfiles/business-central#27]
I'm running this image with docker-compose from https://github.com/jboss-dockerfiles/business-central/blob/7.36.0.Final/docker-compose-examples/jbpm-full-mysql.yml

I tried following the instructions from https://github.com/jboss-dockerfiles/business-central/blob/7.36.0.Final/server/README.md to change the REST API hostname by setting the KIE_SERVER_LOCATION environment variable. However, even though the variable is set inside the container (docker exec -ti ...) and applied to the process ("-D..."), Business Central would still show the old URL (localhost). I found out that the property is set also inside the standalone.xml WildFly configuration file, and that seems to over-ride the environment variable.

Another thing is that bin/jbpm-mysql-config.cli is run every time the container is started (by bin/update_db_config.sh which is in turn run by bin/start_jbpm-wb.sh), resetting that property in standalone.xml to the localhost value, even if I edit it manually.
The only fix that worked for me was setting the property in bin/jbpm-mysql-config.cli to the value I needed.

**Comment by mbiarnes** [comment]
Hi folks,
Can you please send your questions to drools-usage@gmail.com or drools-setup@gmail.com - I think here is more people that may help you.
Thank you.

**Comment by CariSeniorProgrammer** [comment]
Can confirm this behavior.
