### ISSUE TITLE
Unable to create new project

### ISSUE THREAD

**Issue by cameronew** [jboss-dockerfiles/business-central#4]
When creating a new project receive the following error:

Unable to complete your request. The following exception occurred: org.apache.maven.project.ProjectBuildingException: 1 problem was encountered while building the effective model [FATAL] Non-readable POM : input contained no data @ for project .

**Comment by cameronew** [comment]
[logextract.txt](https://github.com/jboss-dockerfiles/business-central/files/3393823/logextract.txt)

**Comment by mbiarnes** [comment]
> When creating a new project receive the following error:
> 
> Unable to complete your request. The following exception occurred: org.apache.maven.project.ProjectBuildingException: 1 problem was encountered while building the effective model [FATAL] Non-readable POM : input contained no data @ for project .

Hi cameronew,

Can you please forward this to drools-usage@gmail.com?
I think on this channel you will get more help.
I would say this ha to do more with the behaviour of creating a new project with business central then with the docker images itself.

**Comment by shabnamshaik** [comment]
Hi,

I am also getting the same issue.

Unable to complete your request. The following exception occurred: org.apache.maven.project.ProjectBuildingException: 1 problem was encountered while building the effective model [FATAL] Non-readable POM : input contained no data @ for project .


Could you please help how to resolve it?

**Comment by cameronew** [comment]
Hi - Basically when you create a new project the jbpm system tries to connect to the internet and times out. If your computer running docker is connected to the internet when you create a new project it will download the necessary files and you should be able to work off-line from then on....as I have done.

Hope this helps :)

**Comment by mbiarnes** [comment]
Hi folks,
Can you please send your questions to drools-usage@gmail.com or drools-setup@gmail.com - I think here is more people that may help you. 
Thank you.

**Comment by DevotedTangLiu** [comment]
Well I am getting the same issue.

**Comment by cchentyro** [comment]
hi, @mbiarnes , email address is invalid ....

**Comment by KedrGitHub** [comment]
Well I am getting the same issue and I saw, mbiarnes closed this. What the problem was and how to solve it???

**Comment by KedrGitHub** [comment]
I used docker image jboss/drools-workbench-showcase:latest

**Comment by mbiarnes** [comment]
@KedrGitHub 
What happens if you change `latest` by `7.73.0.Final`?

**Comment by KedrGitHub** [comment]
7.73.0.Final not Found in dockerhub. The last version is 7.17.0.Final. Last pushed 4 years ago.

**Comment by mbiarnes** [comment]
look at https://quay.io/repository/kiegroup/business-central-workbench (for business-central-workbench) - out images are on quay.io - for at least the last years

**Comment by mbiarnes** [comment]
@KedrGitHub where are you looking exactly?

**Comment by KedrGitHub** [comment]
https://hub.docker.com/

**Comment by mbiarnes** [comment]
for years we don't publish our docker images there - - 
look at 
https://quay.io/repository/kiegroup/business-central-workbench
https://quay.io/repository/kiegroup/business-central-workbench-showcase
https://quay.io/repository/kiegroup/kie-server
https://quay.io/repository/kiegroup/kie-server-showcase
https://quay.io/repository/kiegroup/jbpm-server-full
and also latest should point to 7.47.0.Final

**Comment by KedrGitHub** [comment]
Thanks for your help!
