### ISSUE TITLE
Login failed: Not Authorized

### ISSUE THREAD

**Issue by ckvtvm-arch** [jboss-dockerfiles/business-central#42]
I am trying this for last several days, but not successful. can you please help in logging in for the first time. I was able to do so in the past, but now i am failing.

Added the user name and password as shown below:

./add-user.sh -a --user <username> --password <password> --role admin 

Added user 'encounter' to file '/opt/eap/standalone/configuration/application-users.properties'
Added user 'encounter' to file '/opt/eap/domain/configuration/application-users.properties'
Added user 'encounter' with groups admin to file '/opt/eap/standalone/configuration/application-roles.properties'
Added user 'encounter' with groups admin to file '/opt/eap/domain/configuration/application-roles.properties'

Login failed: Not Authorized

**Comment by steve-hexagon** [comment]
Did you get this working? What was the key?
