### ISSUE TITLE
customize kie-server standalone.xml 

### ISSUE THREAD

**Issue by kmcrawford** [jboss-dockerfiles/business-central#43]
I have a question about the documentation in the README below:

![image](https://user-images.githubusercontent.com/40531/104017181-a5420680-5185-11eb-886c-e4391cf2ae45.png)

Should `standalone.xml` be updated or should it be `standalone-full.xml`?  

As it looks like the `standalone-full.xml` is referenced during startup vs `standalone.xml`

https://github.com/jboss-dockerfiles/business-central/blob/master/kie-server/base/README.md

@sboddu

**Comment by mbiarnes** [comment]
Hi Ken,

the standalone-full.xml is customized to have created users and roles an to run this images straight away ([kie-server-showcase](https://hub.docker.com/r/jboss/kie-server-showcase/)) - the standalone.xml is not customized yet [kie-server](https://hub.docker.com/r/jboss/kie-server/) - so for extending a image I would use this instead of the pre-configured standalone-full.xml.

**Comment by sboddu** [comment]
Hi Michael,

The base version of kie-server does use the standalone-full.xml file in the start_kie-wb.sh file. But as per your documentation below it was suggested to use the standalone.xml file. So my question is the documentation is misleading or the start_kie-wb.sh file wrong ?

https://github.com/jboss-dockerfiles/business-central/blob/master/kie-server/base/etc/start_kie-wb.sh




[cid:df451adb-7006-43aa-be7e-1242893ac5ad]

Also when i compared the standalone.xml and standalone-full.xml, the only major difference i could see is the activemq configuration. Please let me know whether standalone.xml or standalone-full.xml file needs to be referenced for the kie-server/base image

Thanks
Srikanth

________________________________

**Comment by mbiarnes** [comment]
Hi Srikanth,
Using `standalone.xml` or `standalone-full.xml` it is nearly the same. Except that for `standalone-full.xml` there are already defined users and roles. 
As said in a previous message, `standalone-full.xml` is already "customized", so using predefined users and roles you can start the `*.war` directly with `start.sh`.
If you want to use `standalone.xml` you have first to create a user with a rol, so you can access the app and see the right screens. You have to change simply the `start.sh` that should point to the `standalone.xml` (if you want to use this). Or you use the `standalone-full.xml` and ignore the pre-configued user which already exist. Up to you. 
What I want to say is, that the kie-sever works with both `.xml `. 
The `standalone-full.xml` initially was created for testing the behaviour of the application.

**Comment by sboddu** [comment]
Thanks Michael for the clarifications

________________________________
