### ISSUE TITLE
Unable to import private projects

### ISSUE THREAD

**Issue by dana-c0914** [jboss-dockerfiles/business-central#6]
Hi,

I set up the business-central showcase image, version 7.24.0.Final and it seems to have a problem with importing projects.
I was trying to import projects from a gitlab private repository. The authentication parts works and I can see the projects available in the repository but after selecting which projects I want to import I get a _CloneException_ because I am _not authorized_. The issue seems to be similar to this one: https://issues.jboss.org/browse/RHPAM-1617. 
I did not test this issue with a public repository.

In version 7.23.0.Final everything seems to be working.

**Comment by mbiarnes** [comment]
Hi folks,
Can you please send your questions to drools-usage@gmail.com or drools-setup@gmail.com - I think here is more people that may help you.
Thank you.
