### ISSUE TITLE
How to use custom workitem handlers

### ISSUE THREAD

**Issue by nootPaola** [jboss-dockerfiles/business-central#62]
Hi,
I'd like to know how to use self implemented workitem handlers? Is there anithing to change in the docker file or some other image to download in order to host workitem handlers classe?

Thanks,
Laura

**Comment by mbiarnes** [comment]
Hi Laura,
Please report this issue to[ jBPM Setup](https://groups.google.com/forum/#!forum/jbpm-setup) or [jBPM Usage](https://groups.google.com/forum/#!forum/jbpm-usage) Google groups.
