### ISSUE TITLE
Unable to pull business-central showcase docker image from the registry

### ISSUE THREAD

**Issue by xwrs** [jboss-dockerfiles/business-central#67]
running this command from the readme instructions

`docker run -p 8080:8080 -p 8001:8001 -d --name jbpm-workbench quay.io/kiegroup/kie-business-central-workbench-showcase:latest`

leads to the following error

Unable to find image 'quay.io/kiegroup/kie-business-central-workbench-showcase:latest' locally
docker: Error response from daemon: unauthorized: access to the requested resource is not authorized.
See 'docker run --help'.

**Comment by mbiarnes** [comment]
@xwrs SORRY. try 
`docker run -p 8080:8080 -p 8001:8001 -d --name jbpm-workbench quay.io/kiegroup/business-central-workbench-showcase:latest`
Difference is the superflous `kie` - absolutely my error. ThanX that you reported this.
