### ISSUE TITLE
Constantly logging warning: Unable to load key store. Using password from configuration

### ISSUE THREAD

**Issue by dana-c0914** [jboss-dockerfiles/business-central#7]
Hi

I am using the business-central-showcase:7.23.0.Final image and the kie-server-showcase:7.23.0.Final together. I can see the server in the server configurations from the business central but every 5 seconds I receive a warning in the logs of the business central container : _Unable to load key store. Using password from configuration_.

A pull request was opened here for this issue: https://github.com/kiegroup/droolsjbpm-integration/pull/1800 (this one got closed) and here https://github.com/kiegroup/kie-wb-distributions/pull/911. 
This last one was merged and included in the 7.21.0.Final release yet in the standalone.xml file I cannot find the new properties being set only the ones that were there before as well. Also I cannot find the _jBPMKeystore.jceks_ file.

I am not sure if there are any configurations that I need to take care of. I tried adding the properties in the jbpm-custom.cli and building a new image but then I have the problem that the  _jBPMKeystore.jceks_ is not found. 

Would be great if somebody could point me to a configuration that I need to do if any. Thanks

**Comment by mbiarnes** [comment]
Hi,
Try also to send your requests to drools-usage@googlegroups.com or drools-setup@googlegroups.com.
There is a lot of people that should help you with this.

**Comment by MarianMacik** [comment]
@dana-c0914 Hi, I have noticed your message only now after going through older JIRAs. The issue you observed should be fixed by https://github.com/kiegroup/droolsjbpm-integration/pull/1903 (7.28.0.Final when released). The reason why you see it is that the docker image doesn't have a keystore configured. The mentioned PR will fix this by displaying the warning just once.

**Comment by dana-c0914** [comment]
@mbiarnes @MarianMacik thank you for your answers.
I did not continue with this configuration and didn't try anymore to configure the keystore so I will close the issue. Thanks again!
