### ISSUE TITLE
Does jbpm-server-full support High Availability ?

### ISSUE THREAD

**Issue by hohuyphuong** [jboss-dockerfiles/business-central#75]
Hello Michael,

I setup jbpm-server-full follow guide https://github.com/jboss-dockerfiles/business-central/blob/main/server/README.md
To ensure high availability for jbpm-server-full, How to deploy jbpm-server-full to supports failover or load balancing features?

Thank you.

**Comment by mbiarnes** [comment]
Hi hohuyphuong,

I would say the load balancing in a docker environment is a docker issue. Look here:

**Comment by hohuyphuong** [comment]
Hello Michael,

Thanks for your response, skipping the load balancing issue.

In your example, jbpm-server-full is a WildFly instance and run as a "standalone server".
It is perfectly possible to launch multiple standalone server instances and have them form an HA cluster.
Can you update Dockerfile for the case **start multiple standalone server with full-ha profile**. ?
**Example:**  $ ./standalone.sh -c standalone-full-ha.xml
I read the information about WildFly HA from: http://www.mastertheboss.com/jbossas/jboss-cluster/managing-high-availability-with-wildfly/
<img width="868" alt="WildFly-HA" src="https://user-images.githubusercontent.com/26562329/153569595-75b11269-9e8b-4903-8b9b-35ce92729ee3.png">

**Comment by mbiarnes** [comment]
https://github.com/jboss-dockerfiles/business-central/pull/76

**Comment by hohuyphuong** [comment]
Hello @mbiarnes 

I checkout latest code and start jbpm-server-full without any errors, but I cannot login with users and role default (wbadmin/wbadmin). Did I miss something?
Please have a look:
<img width="1384" alt="log-start-jbpm" src="https://user-images.githubusercontent.com/26562329/153989818-d32eb51c-9492-47be-9ef6-b21eaf37b0f5.png">

<img width="1315" alt="login-failed" src="https://user-images.githubusercontent.com/26562329/153989821-f1ae8a64-2c67-4e73-971d-5cc6b2654252.png">

**Comment by mbiarnes** [comment]
krisv/krisv

**Comment by hohuyphuong** [comment]
Hello @mbiarnes 
Start jbpm-server-full container with standalone-full-ha.xml 
I tried list users: wbadmin, krisv, john,sales-rep,katy, jack but the result is FAILED login.
<img width="965" alt="lis-users-example" src="https://user-images.githubusercontent.com/26562329/154024732-7135691d-d583-4364-8bd2-eb9cd790ad1f.png">

I try custom Dockerfile, start without  standalone-full-ha.xml, and login again with the list users, the results is SUCCESS.
```
exec ./standalone.sh -b $JBOSS_BIND_ADDRESS $EXTRA_OPTS -Dorg.kie.server.location=$KIE_SERVER_LOCATION -Dorg.kie.server.id=$KIE_SERVER_ID -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true
```
I guess the problem when switch mode from  ./standalone.sh to  ./standalone.sh  -c standalone-full-ha.xml
What do you think?

Thanks,

**Comment by mbiarnes** [comment]
could be.
Please look at the doc of the docker images. I think you should add something to the standalone-full-ha.xml.
Compare this one and the standalone-full.xml.
