### ISSUE TITLE
Installing 7.61 and later fails on AWS Fargate

### ISSUE THREAD

**Issue by dnz-bdeboer** [jboss-dockerfiles/business-central#85]
I have an odd issue where installing 7.60 and later on AWS Fargate fails. Previous versions work fine. Does anyone have a suggestion on what could be wrong? There are endless stack dumps, so not sure repeating them here will help, but just one error that seems relevant:

```
WFLYCTL0186:   Services which failed to start:      service jboss.deployment.unit."business-central.war".WeldStartService: Failed to start service

```

**Comment by mbiarnes** [comment]
Hi dnz-bdeboer,
The docker images are always tested before uploading them to docker.io or quay.io (from version 7.61.0.Final) on.
I am a kind of lost: are you installing the docker images? If so,  which one exactly?  Or are you deploying the `business-central.war` version 7.60.0.Final to a `WildFly 23` ? 
In this case it is not a docker image, so I would ask at drools-usage@googlegroups.com or drools-setup@googlegroups.com.
AFAIK there is no docker image for 7.60.0.Final (https://hub.docker.com/r/jboss/business-central-workbench-showcase/tags)
Can you explain a little bit more what exactly you're doing?
ThanX

**Comment by dnz-bdeboer** [comment]
I'm using the docker images, such as quay.io/kiegroup/jbpm-server-full:7.66.0.Final. Works fine with local docker, refuses to work on AWS Fargate.

So the last docker version that works for me is `jboss/jbpm-server-full:7.59.0.Final`. As you pointed correctly there's no 7.60 so have changed the title to avoid confusing with others, so when I change this to `jboss/jbpm-server-full:7.61.0.Final` it simply does not start/install on AWS Fargate.

**Comment by mbiarnes** [comment]
Hi,
I don't have experience with AWS Fargate. Sorry.
I don't know what this can be.
In the notes of the Readme is edited (among other note):

- No support for clustering
- This image is not intended to be run on cloud environments such as RedHat OpenShift or Amazon EC2, as it does not meet all the requirements.
- Please give us your feedback or report a issue at [jBPM Setup](https://groups.google.com/forum/#!forum/jbpm-setup) or [jBPM Usage](https://groups.google.com/forum/#!forum/jbpm-usage) Google groups.

**Comment by dnz-bdeboer** [comment]
Currently this issue is solved. Version 7.67 installs. I probably also made some other changes/fixes to the environment. One thing I could have done wrong for example is forgetting that if you use the showcase version, the https certificates no longer work, this compared to the base version where the https certificate generation does work. It doesn't explain the errors I saw exactly, but at least I can let the world know that 7.67 works on AWS Fargate.
