### ISSUE TITLE
Readme.md - The link not work

### ISSUE THREAD

**Issue by hohuyphuong** [jboss-dockerfiles/business-central#88]
@mbiarnes  The Readme.md at https://github.com/jboss-dockerfiles/business-central/tree/main/base#readme

The link not work, return **404** : https://github.com/kiegroup/business-central/tree/7.67.0.Final/showcase/etc/kie-fs-realm-users 

<img width="1106" alt="bussiness-central-readme" src="https://user-images.githubusercontent.com/26562329/160974187-3f8781af-c7ce-4a15-a3f9-47622cfa4415.png">

Please check, thanks.

**Comment by mbiarnes** [comment]
hohuyphuong,
You're right! Please change in the not working link "kiegroup" by "jboss-dockerfiles"
https://github.com/jboss-dockerfiles/business-central/tree/7.67.0.Final/showcase/etc/kie-fs-realm-users.
Will change this in the docks.
